### ISSUE TITLE
Error when import `voxel_pooling_ext` package

### ISSUE THREAD

**Issue by SeaBird-Go** [megvii-research/CVPR2023-UniDistill#3]
Hi, thanks for sharing this code.

I found you just upload the `voxel_pooling_ext.cpython-36m-x86_64-linux-gnu.so` file for this voxel_pooling_ext module. However when I ran the code, I got the error:
```bash
ImportError: ~/CVPR2023-UniDistill/unidistill/layers/blocks_3d/mmdet3d/voxel_pooling_ext.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZNK2at6Tensor8data_ptrIfEEPT_v
```
Could you help me solve this problem or share the source code about this module?

**Comment by FudongGe** [comment]
Good work! But I met the same 'import' question. And could you introduce how you get the file 'voxel_pooling_ext.cpython-36m-x86_64-linux-gnu.so'? Thanks very much!

**Comment by kebijuelun** [comment]
Hi, thank you for your attention to our work.  @FudongGe @SeaBird-1995 

This issue is likely caused by a mismatch in the Python version. The version we currently need is as follows:

Install python3.6 + CUDAv10.2 + CUDNNv8.0.4 + [pytorch](https://pytorch.org/)(v1.9.0)
```bash
pip3 install mmcv-full==1.4.2 -f https://download.openmmlab.com/mmcv/dist/cu102/torch1.9.0/index.html
pip3 install mmdet==2.20.0
# download mmdet3d whl from https://drive.google.com/file/d/1y6AjikFQGc400dTim9IIFdvR8RNvnPId/view?usp=share_link
pip3 install mmdet3d-0.18.0-cp36-cp36m-linux_x86_64.whl
```

The most convenient reproduction method currently is to use the Conda environment to ensure that the Python version is consistent with what we described. (for emample: `conda create -n unidistill python==3.6; conda activate unidistill`)

Sorry for any inconvenience. And we will confirm whether the relevant source code here can be opened source recently, and if so, it can reduce the version restrictions.

**Comment by kebijuelun** [comment]
Hi, thank you for your attention to our work.  @FudongGe @SeaBird-1995 

This issue is likely caused by a mismatch in the Python version. The version we currently need is as follows:

Install python3.6 + CUDAv10.2 + CUDNNv8.0.4 + [pytorch](https://pytorch.org/)(v1.9.0)
```bash
pip3 install mmcv-full==1.4.2 -f https://download.openmmlab.com/mmcv/dist/cu102/torch1.9.0/index.html
pip3 install mmdet==2.20.0
# download mmdet3d whl from https://drive.google.com/file/d/1y6AjikFQGc400dTim9IIFdvR8RNvnPId/view?usp=share_link
pip3 install mmdet3d-0.18.0-cp36-cp36m-linux_x86_64.whl
```

The most convenient reproduction method currently is to use the Conda environment to ensure that the Python version is consistent with what we described. (for emample: `conda create -n unidistill python==3.6; conda activate unidistill`)

Sorry for any inconvenience. And we will confirm whether the relevant source code here can be opened source recently, and if so, it can reduce the version restrictions.

**Comment by SeaBird-Go** [comment]
Got that. Thanks for your reply. Hopy for openining the original sources to ease the environment constraints.
